services:

  vllm-qwen:
    image: vllm/vllm-openai:latest

    container_name: vllm-qwen

    runtime: nvidia

    ports:
      - "8000:8000"

    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface

    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}

    command: >
      --model Qwen/Qwen2.5-7B-Instruct
      --gpu-memory-utilization 0.45
      --max-model-len 4096
      --api-key EMPTY

  vllm-mistral:
    image: vllm/vllm-openai:latest

    container_name: vllm-mistral

    runtime: nvidia

    ports:
      - "8001:8000"

    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface

    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}

    command: >
      --model mistralai/Mistral-7B-Instruct-v0.3
      --gpu-memory-utilization 0.45
      --max-model-len 4096
      --api-key EMPTY

  poetry-app:
    build: ./app

    container_name: poetry-app

    ports:
      - "8501:8501"

    depends_on:
      - vllm-qwen
      - vllm-mistral