version: "3.9"

services:
  model-server:
    build: ./model-server
    container_name: model-server

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface

    environment:
      - HF_TOKEN=${HF_TOKEN}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    restart: unless-stopped

  poetry-app:
    build: ./app
    container_name: poetry-app

    ports:
      - "8501:8501"

    depends_on:
      - model-server

    restart: unless-stopped
